### ISSUE TITLE
Enter Security Password: 

### ISSUE THREAD

**Issue by TheKingLol** [mutalisk999/xmrpool#6]
**#### System information**
Ubuntu 22.04.3 LTS
Monero version: Monero 'Fluorine Fermi' (v0.18.3.1-release)

**Stratum commit hash:**
Latest Tag: v0.1.1
Latest Tag Commit SHA1: 4633784604f2927434ef49bc4c582c34fd8157ce
Latest Commit SHA1: 4633784604f2927434ef49bc4c582c34fd8157ce
Build Time: 2023-10-24 10:09:59
Release Type: release

OS & Version: Linux

#### Expected behaviour
To find a way to get the security password or create it (forgive me if i am not making any sense as this is new to me)

#### Actual behaviour
2023/10/24 11:10:27 Loading config: /home/user/monero-project/xmrpool/config.json
2023/10/24 11:10:27 logSetLevel: 0
2023/10/24 11:10:27 infoFile: logs/info.log
2023/10/24 11:10:27 errorFile: logs/error.log
2023/10/24 11:10:27 shareFile: logs/share.log
2023/10/24 11:10:27 blockFile: logs/block.log
[I] 2023/10/24 11:10:27.806912 platform_linux.go:13: Rlimit Current: 1048576
Enter Security Password: 

#### Steps to reproduce the behaviour
Build on linux and run

#### Backtrace

````
[backtrace]
````

**Comment by mutalisk999** [comment]
my bad, i will update the detail tutorial later.

**Comment by TheKingLol** [comment]
Thank you,
Take it easy and all is good!

**Comment by mutalisk999** [comment]
@TheKingLol Please checkout the latest Tutorial.


* About `Security Password`:

We use `Security Password` to prevent our important configuration information from being viewed or modified.
So we encrypt some important configurations in config.json.

    addressEncrypted
    redis.passwordEncrypted or redisFailover.passwordEncrypted

* How to encrypt/decrypt

Use function `TestAe64Encode` and `TestAe64Decode` from model `util` in this project.

**Comment by TheKingLol** [comment]
Thanks ill look into it now!

**Comment by TheKingLol** [comment]
is there also a way to obtain an encryptedaddress?

**Comment by mutalisk999** [comment]
Recently No, LOL
Maybe sometime i will make an encrypt/decrypt tool.

**Comment by TheKingLol** [comment]
Ah ok so there is no way to get an address to put in "addressEncrypted":?

**Comment by mutalisk999** [comment]
First to get one XMR address, then put it into function TestAe64Encode, and run TestAe64Encode, your will get `addressEncrypted`.

```
func TestAe64Encode(t *testing.T) {
	src := []byte("Your XMR address")
	key := []byte("Your Security Password")
	dst, _ := Ae64Encode(src, key)
	fmt.Println(dst)
}
```

**Comment by TheKingLol** [comment]
Ah i see and what is src2 for?
Sorry if I am being a nuicance

**Comment by mutalisk999** [comment]
It's My pleasure. LOL
In fact src2 is no different with src in function, just used to encrypt more src at one time.

**Comment by TheKingLol** [comment]
I understand now thank you so much.
Do you think the encryption and decryption part of the code should be necessary or do you think that running a pool requires this level of security?

**Comment by mutalisk999** [comment]
Maybe it is the pool owner's consideration. LOL

**Comment by TheKingLol** [comment]
I definitely haven't used go before and I find it difficult to encrypt my address.
If I remove the lines of code that require me to use an encrypted address do you think it will work?

**Comment by mutalisk999** [comment]
It is definitely OK

**Comment by TheKingLol** [comment]
When I run ae64_test.go I get ```undefined: Ae64Encode```
I am extremely sorry if im taking up too much of your time

**Comment by mutalisk999** [comment]
It doesn't matter. 

Try this:
```
cd util
go test
```

Maybe you will see:
```
bg2Z2F+OA6LTR5VQjsOiLOH2YqSiFbETBQWlZ25nt51UsZrrRqWSvWJT4yX6Oz5r
nuaXMECKl3fLIRwzJyKXHA==
0xae17a0398694c94d4f861c5aa1b215adbf0d48b5

```

**Comment by TheKingLol** [comment]
Thank you so much it worked!
I am really sorry I took alot of time your busy day

**Comment by mutalisk999** [comment]
Congratulations!
It's just Ok.
Wish you have a good day.

**Comment by TheKingLol** [comment]
Will it make a difference if it isn't the same digit as the config_example?

**Comment by mutalisk999** [comment]
It's ok, In fact we use config.json by default.

**Comment by TheKingLol** [comment]
Ah the password still doesnt change

**Comment by mutalisk999** [comment]
Your can change your own password in TestAe64Encode, and this password is your own Security Password.

**Comment by TheKingLol** [comment]
Its seems though the password that works is 12345678

**Comment by mutalisk999** [comment]
Because 12345678 is the default password in the testcase, You can change it.
This password must be the same with the Security Password you input from terminal when the binary xmrpool runs.
