### ISSUE TITLE
Password encryption

### ISSUE THREAD

**Issue by MiningCryptoLive** [mutalisk999/xmrpool#8]
Trying to find out how to encrypt the wallet address and password for redis. Is the project still compatible with the latest monerod?

**Comment by mutalisk999** [comment]
1.About encryption and decryption, maybe it (https://github.com/PowPool/xmrpool/blob/main/util/ae64_test.go) can helps.
2.This repo was updated once in monerod v0.18.3.1. Theoretically, it should be compatible now.
